#!/usr/bin/env python3
"""Generate fonts_latin1.h for PaperType: DejaVu Sans Mono, glyphs 0x20-0xFF,
in three sizes x four styles, as LovyanGFX-compatible GFXfont tables.

Run on any machine with Pillow and the DejaVu fonts (Linux has them at
/usr/share/fonts/truetype/dejavu; on macOS/Windows point FONTS at TTF paths).
Output: PaperType/fonts_latin1.h next to the sketch.
"""

from PIL import Image, ImageDraw, ImageFont
import os
import sys

DEJAVU = "/usr/share/fonts/truetype/dejavu"
FONTS = {
    "":   os.path.join(DEJAVU, "DejaVuSansMono.ttf"),
    "B":  os.path.join(DEJAVU, "DejaVuSansMono-Bold.ttf"),
    "I":  os.path.join(DEJAVU, "DejaVuSansMono-Oblique.ttf"),
    "BI": os.path.join(DEJAVU, "DejaVuSansMono-BoldOblique.ttf"),
}
SIZES = {"9": 15, "12": 20, "18": 30}       # px em sizes ~ FreeMono 9/12/18pt
FIRST, LAST = 0x20, 0xFF

# Internal slots 0x80-0x8B carry the Esperanto letters (they're outside
# Latin-1; the firmware maps them to real code points when saving files).
SUBST = {0x80 + i: ch for i, ch in enumerate("ĉĈĝĜĥĤĵĴŝŜŭŬ")}

out = []
out.append("// Generated by tools/make_fonts.py - DejaVu Sans Mono, Latin-1")
out.append("// (glyphs 0x20-0xFF). Do not edit by hand.")
out.append("#pragma once")
out.append("")

total = 0
for sz_name, px in SIZES.items():
    for style, path in FONTS.items():
        f = ImageFont.truetype(path, px)
        ascent, descent = f.getmetrics()
        adv = int(round(f.getlength("M")))
        name = f"DejaVuMono{sz_name}{style}"
        bitmap = bytearray()
        glyphs = []
        for code in range(FIRST, LAST + 1):
            ch = SUBST.get(code, chr(code))
            canvas = Image.new("L", (px * 3, px * 3), 0)
            d = ImageDraw.Draw(canvas)
            d.text((px, px), ch, font=f, fill=255)   # draw origin at (px, px)
            bbox = canvas.getbbox()
            if bbox is None:                          # blank glyph (space, nbsp)
                glyphs.append((len(bitmap), 0, 0, adv, 0, 0))
                continue
            x0, y0, x1, y1 = bbox
            w, h = x1 - x0, y1 - y0
            xoff = x0 - px
            yoff = (y0 - px) - ascent                 # top relative to baseline
            crop = canvas.crop(bbox)
            bits = []
            pix = crop.load()
            for yy in range(h):
                for xx in range(w):
                    bits.append(1 if pix[xx, yy] >= 128 else 0)
            offset = len(bitmap)
            for i in range(0, len(bits), 8):
                byte = 0
                for j, bit in enumerate(bits[i:i + 8]):
                    if bit:
                        byte |= 0x80 >> j
                bitmap.append(byte)
            glyphs.append((offset, w, h, adv, xoff, yoff))
        y_adv = ascent + descent
        total += len(bitmap) + len(glyphs) * 7
        out.append(f"static const uint8_t {name}_Bitmaps[] PROGMEM = {{")
        for i in range(0, len(bitmap), 16):
            out.append("  " + ",".join(f"0x{b:02X}" for b in bitmap[i:i + 16]) + ",")
        out.append("};")
        out.append(f"static const lgfx::v1::GFXglyph {name}_Glyphs[] PROGMEM = {{")
        for g in glyphs:
            out.append("  {%d,%d,%d,%d,%d,%d}," % g)
        out.append("};")
        out.append(f"static const lgfx::v1::GFXfont {name} = "
                   f"{{ (uint8_t*){name}_Bitmaps, (lgfx::v1::GFXglyph*){name}_Glyphs, "
                   f"0x{FIRST:02X}, 0x{LAST:02X}, {y_adv} }};")
        out.append("")

dst = os.path.join(os.path.dirname(__file__), "..", "BYOBYOK", "fonts_latin1.h")
with open(dst, "w") as fh:
    fh.write("\n".join(out))
print(f"{dst}: 12 fonts, ~{total // 1024} KB of tables")
